### ISSUE TITLE
Custom entities

### ISSUE THREAD

**Issue by RoskaricRo** [killer0071234/ha-hiq#174]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/killer0071234/ha-hiq/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Need something to change or display some custom PLC variables

### Describe the solution you'd like

Can you make feature that will make custom PLC variable as Entity. As an example I have a custom program part/variables for sunset/sunrise time on mine PLC (Cybro2), which is calculated on PLC and its not very accurate.   

### Describe alternatives you've considered

This can be done, with usageof web request to SCGI server, but its not sosofisticated as HIQ addon.

### Additional context

Dont know maybe you have already done such a feature.

**Comment by killer0071234** [comment]
Hi @RoskaricRo!

Write own tags in the PLC is already possible via a service call.
See [services section](https://github.com/killer0071234/ha-hiq?tab=readme-ov-file#services) write tag on the github page.

The possibility to add custom plc tags as sensor or binary sensor is currently not implemented.

BR Daniel

**Comment by killer0071234** [comment]
Hi @RoskaricRo !

A short update on your request to write / read custom PLC variables.

Soon there will be a new version which allows to add custom variables for read from the PLC.
Is that sufficient for your requirements?
Did you tried to use the service call `Write tag` to set your custom variables in the PLC?

BR Daniel

**Comment by RoskaricRo** [comment]
Hi,
  I check what you wrote about write tag. But to be honest I did not know
how to use it. Will check again

Best regards, Robert

V sre., 15. maj 2024, 23:14 je oseba Daniel Gangl ***@***.***>
napisala:

**Comment by killer0071234** [comment]
Hi @RoskaricRo !

You can set values in the plc as shown below:
![grafik](https://github.com/killer0071234/ha-hiq/assets/31815106/72da71db-118f-4fd7-8c3a-e94e8384c720)

BR Daniel

**Comment by RoskaricRo** [comment]
Hi,
  Finally I found the time to test everything. Custom read tag works and a service write tag too. Finally I can set a clock on my "broken" cybro-2 (well its working without problems, but cannot store RTC).
Well done, Thanks.

Best regards, 
  Robert

**Comment by killer0071234** [comment]
Very good! 
Glad to hear that you managed it to get it working.
BR Daniel
